// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6NUo3KaN_0S8epjcD5YRiUStXGB1PTk',
    appId: '1:526639212806:web:a9ecf47edd3a1446ec1687',
    messagingSenderId: '526639212806',
    projectId: 'jenan-4bcc7',
    authDomain: 'jenan-4bcc7.firebaseapp.com',
    storageBucket: 'jenan-4bcc7.firebasestorage.app',
    measurementId: 'G-ML7GE7NDBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGiLgHC6aSegQq69rNKKjoW2C76vD3Z6o',
    appId: '1:526639212806:android:fe1233845dd43788ec1687',
    messagingSenderId: '526639212806',
    projectId: 'jenan-4bcc7',
    storageBucket: 'jenan-4bcc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeRCVvoosa2dJd-OfJUiravZN9yZShZ5E',
    appId: '1:526639212806:ios:e01a08cb0bf569c2ec1687',
    messagingSenderId: '526639212806',
    projectId: 'jenan-4bcc7',
    storageBucket: 'jenan-4bcc7.firebasestorage.app',
    iosBundleId: 'com.example.jenanAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeRCVvoosa2dJd-OfJUiravZN9yZShZ5E',
    appId: '1:526639212806:ios:e01a08cb0bf569c2ec1687',
    messagingSenderId: '526639212806',
    projectId: 'jenan-4bcc7',
    storageBucket: 'jenan-4bcc7.firebasestorage.app',
    iosBundleId: 'com.example.jenanAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6NUo3KaN_0S8epjcD5YRiUStXGB1PTk',
    appId: '1:526639212806:web:e152ed458cf64303ec1687',
    messagingSenderId: '526639212806',
    projectId: 'jenan-4bcc7',
    authDomain: 'jenan-4bcc7.firebaseapp.com',
    storageBucket: 'jenan-4bcc7.firebasestorage.app',
    measurementId: 'G-QV7EJ4931H',
  );
}
